#!/bin/python
from openrgb import OpenRGBClient
from pynput.keyboard import Key, Listener

class Handler():
    def __init__(self):
        self.mod = False
        self.ctrl = False
        self.shift = False
        self.rgb = OpenRGBClient()

        for i in ["Mod", "Mod+Shift", "Mod+Ctrl", "None"]:
            try:
                self.rgb.load_profile(i)
            except ValueError:
                self.rgb.save_profile(i)

    def updateKeys(self, key, press):
        if key == Key.cmd:
            self.mod = press
        if key == Key.ctrl:
            self.ctrl = press
        if key == Key.shift:
            self.shift = press
        self.choose_profile()

    def choose_profile(self):
        if self.mod:
            if not (self.shift or self.ctrl):
                self.rgb.load_profile("Mod")
            elif self.shift:
                self.rgb.load_profile("Mod+Shift")
            elif self.ctrl:
                self.rgb.load_profile("Mod+Ctrl")
        else:
            self.rgb.load_profile("None")

if __name__ == "__main__":
    h = Handler()
    def on_press(key):
        h.updateKeys(key, True)

    def on_release(key):
        h.updateKeys(key, False)

    with Listener(on_press=on_press, on_release=on_release) as listener:
        listener.join()
