#!/bin/sh

BLANK=$(xrcat "lock.color0")
CLEAR='#ffffff22'
DEFAULT=$(xrcat "lock.color4")
TEXT=$(xrcat "lock.color2")
WRONG=$(xrcat "lock.color1")
VERIFYING=$(xrcat "lock.color5")

i3lock \
--color=$BLANK             \
--insidever-color=$BLANK   \
--ringver-color=$VERIFYING \
                           \
--insidewrong-color=$BLANK \
--ringwrong-color=$WRONG   \
                           \
--inside-color=$BLANK      \
--ring-color=$DEFAULT      \
--line-color=$BLANK        \
--separator-color=$DEFAULT \
                           \
--verif-color=$TEXT        \
--wrong-color=$TEXT        \
--time-color=$TEXT         \
--date-color=$TEXT         \
--layout-color=$TEXT       \
--keyhl-color=$WRONG       \
--bshl-color=$WRONG        \
                           \
--clock                    \
--indicator                \
--time-str="%H:%M:%S"      \
--date-str="%a %d, %b %Y"
