#!/bin/sh

BLANK=$(xrdb -get color0)
CLEAR='#ffffff22'
DEFAULT=$(xrdb -get color4)
TEXT=$(xrdb -get color2)
WRONG=$(xrdb -get color1)
VERIFYING=$(xrdb -get color5)

i3lock \
--insidever-color=$BLANK     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$BLANK   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%a %d, %b %Y"       \
